//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OLKI.Programme.QBC.src.MainForm.Usercontroles.uscProcControle {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Stringtable {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Stringtable() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OLKI.Programme.QBC.src.MainForm.Usercontroles.uscProcControle.Stringtable", typeof(Stringtable).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sicherungskopie starten ähnelt.
        /// </summary>
        internal static string btnProcessStart_Text__Backup {
            get {
                return ResourceManager.GetString("btnProcessStart_Text__Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Datenwiederherstellung starten ähnelt.
        /// </summary>
        internal static string btnProcessStart_Text__Restore {
            get {
                return ResourceManager.GetString("btnProcessStart_Text__Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Im Zielverzeichnis ablegen, mit angehängtem Datum ähnelt.
        /// </summary>
        internal static string chkLogFileAutoPath_Text__Backup {
            get {
                return ResourceManager.GetString("chkLogFileAutoPath_Text__Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Im Quellverzeichnis ablegen, mit angehängtem Datum ähnelt.
        /// </summary>
        internal static string chkLogFileAutoPath_Text__Restore {
            get {
                return ResourceManager.GetString("chkLogFileAutoPath_Text__Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Protokolldatei für Datenwiederherstellung erstellen ähnelt.
        /// </summary>
        internal static string chkLogFileCreate_Text__Backup {
            get {
                return ResourceManager.GetString("chkLogFileCreate_Text__Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Protokolldatei für Datensicherung erstellen ähnelt.
        /// </summary>
        internal static string chkLogFileCreate_Text__Restore {
            get {
                return ResourceManager.GetString("chkLogFileCreate_Text__Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wurzelordner mit Laufwerksbuchstaben erstellen ähnelt.
        /// </summary>
        internal static string chkRootDirectory_Text__Backup {
            get {
                return ResourceManager.GetString("chkRootDirectory_Text__Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Erster Ordner gibt Laufwerk an ähnelt.
        /// </summary>
        internal static string chkRootDirectory_Text__Restore {
            get {
                return ResourceManager.GetString("chkRootDirectory_Text__Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wählen Sie das Verzeichnis aus in welchem die Datensicherung erzeugt werden soll oder erzeugen Sie ein neues Unterverzeichnis. ähnelt.
        /// </summary>
        internal static string DirectoryBrowser_Description_Backup {
            get {
                return ResourceManager.GetString("DirectoryBrowser_Description_Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wählen Sie das Verzeichnis aus in dem die gesicherten Daten liegen. ähnelt.
        /// </summary>
        internal static string DirectoryBrowser_Description_Restore {
            get {
                return ResourceManager.GetString("DirectoryBrowser_Description_Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zielordner: ähnelt.
        /// </summary>
        internal static string lblDirectory_Text__Backup {
            get {
                return ResourceManager.GetString("lblDirectory_Text__Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Quellordner: ähnelt.
        /// </summary>
        internal static string lblDirectory_Text__Restore {
            get {
                return ResourceManager.GetString("lblDirectory_Text__Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Speicherort für Protokolldatei angeben ähnelt.
        /// </summary>
        internal static string SaveLogFile_Title_Backup {
            get {
                return ResourceManager.GetString("SaveLogFile_Title_Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Speicherort für Protokolldatei angeben ähnelt.
        /// </summary>
        internal static string SaveLogFile_Title_Restore {
            get {
                return ResourceManager.GetString("SaveLogFile_Title_Restore", resourceCulture);
            }
        }
    }
}
