//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OLKI.Programme.QuBC.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Stringtable {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Stringtable() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OLKI.Programme.QuBC.Properties.Stringtable", typeof(Stringtable).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Inkompatible Datei! ähnelt.
        /// </summary>
        internal static string _0x0001c {
            get {
                return ResourceManager.GetString("0x0001c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Projektdatei ist nicht mit dieser Progammversion kompatibel. ähnelt.
        /// </summary>
        internal static string _0x0001m {
            get {
                return ResourceManager.GetString("0x0001m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Projekt speichern? ähnelt.
        /// </summary>
        internal static string _0x0002c {
            get {
                return ResourceManager.GetString("0x0002c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Änderungen an Projekt &quot;{0}&quot; vor dem Schließen speichern?
        ///
        ///Ihre Änderungen gehen verloren, wenn Sie diese nicht speichern. ähnelt.
        /// </summary>
        internal static string _0x0002m {
            get {
                return ResourceManager.GetString("0x0002m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte als Administrator ausführen. ähnelt.
        /// </summary>
        internal static string _0x0003c {
            get {
                return ResourceManager.GetString("0x0003c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sie sollten die Anwendung als Administrator ausführen um Fehler aufgrund verweigerter Zugriffsrechte zu vermeiden. ähnelt.
        /// </summary>
        internal static string _0x0003m {
            get {
                return ResourceManager.GetString("0x0003m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Neues Projekt ähnelt.
        /// </summary>
        internal static string _0x0004 {
            get {
                return ResourceManager.GetString("0x0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler beim Ordnerzugriff. ähnelt.
        /// </summary>
        internal static string _0x0005c {
            get {
                return ResourceManager.GetString("0x0005c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler beim Zugriff auf den Ordner.
        ///
        ///{0} ähnelt.
        /// </summary>
        internal static string _0x0005m {
            get {
                return ResourceManager.GetString("0x0005m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Standardordner der bei der Dateiauswahl angezeigt werden soll ähnelt.
        /// </summary>
        internal static string _0x0006 {
            get {
                return ResourceManager.GetString("0x0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vorgang abgebrochen! ähnelt.
        /// </summary>
        internal static string _0x0007c {
            get {
                return ResourceManager.GetString("0x0007c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Vorgang wurde durch den Nutzer abgebrochen.
        ///
        ///Die Kopie ist wahrscheinlich unvollständig. ähnelt.
        /// </summary>
        internal static string _0x0007m {
            get {
                return ResourceManager.GetString("0x0007m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es ist ein Fehler aufgetreten! ähnelt.
        /// </summary>
        internal static string _0x0008c {
            get {
                return ResourceManager.GetString("0x0008c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Vorgang kann aufgrund eines Fehlers nicht fortgesetzt werden.
        ///
        ///Die Kopie ist wahrscheinlich unvollständig.
        ///
        ///{0} ähnelt.
        /// </summary>
        internal static string _0x0008m {
            get {
                return ResourceManager.GetString("0x0008m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ungespeicherte Änderungen! ähnelt.
        /// </summary>
        internal static string _0x0009c {
            get {
                return ResourceManager.GetString("0x0009c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Im aktuellen Projekt befinden sich ungespeicherte Änderungen. Wollen Sie diese jetzt speichern? ähnelt.
        /// </summary>
        internal static string _0x0009m {
            get {
                return ResourceManager.GetString("0x0009m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Projekt öffnen fehlgeschlagen! ähnelt.
        /// </summary>
        internal static string _0x000Ac {
            get {
                return ResourceManager.GetString("0x000Ac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Datei &quot;{0}&quot; konnte nicht geöffnet werden.
        ///
        ///{1} ähnelt.
        /// </summary>
        internal static string _0x000Am {
            get {
                return ResourceManager.GetString("0x000Am", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Projekt speichern fehlgeschlagen! ähnelt.
        /// </summary>
        internal static string _0x000Bc {
            get {
                return ResourceManager.GetString("0x000Bc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Projekt konnte nicht in die Datei &quot;{0}&quot; gespeichert werden.
        ///
        ///{1} ähnelt.
        /// </summary>
        internal static string _0x000Bm {
            get {
                return ResourceManager.GetString("0x000Bm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Quellordner existiert nicht. ähnelt.
        /// </summary>
        internal static string _0x000C {
            get {
                return ResourceManager.GetString("0x000C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Allgemeiner Fehler beim Kopieren von Dateien im Ordner. ähnelt.
        /// </summary>
        internal static string _0x000D {
            get {
                return ResourceManager.GetString("0x000D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Allgemeiner Fehler beim Kopieren der Datei ähnelt.
        /// </summary>
        internal static string _0x000E {
            get {
                return ResourceManager.GetString("0x000E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Allgemeiner Fehler beim Kopieren der Datei ähnelt.
        /// </summary>
        internal static string _0x000F {
            get {
                return ResourceManager.GetString("0x000F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler beim Öffnen der Quelldatei ähnelt.
        /// </summary>
        internal static string _0x0010 {
            get {
                return ResourceManager.GetString("0x0010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler beim Anlegen der Zieldatei ähnelt.
        /// </summary>
        internal static string _0x0011 {
            get {
                return ResourceManager.GetString("0x0011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler beim Schreiben der Daten in die Zieldatei ähnelt.
        /// </summary>
        internal static string _0x0012 {
            get {
                return ResourceManager.GetString("0x0012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler beim Entfernen von Attributen und Metadaten der bereits existierenden Zieldatei ähnelt.
        /// </summary>
        internal static string _0x0013 {
            get {
                return ResourceManager.GetString("0x0013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler beim Schreiben der Attribute und Metadaten in die Zieldatei ähnelt.
        /// </summary>
        internal static string _0x0014 {
            get {
                return ResourceManager.GetString("0x0014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zählen von Elementen und Daten wird gestartet ähnelt.
        /// </summary>
        internal static string _0x0015 {
            get {
                return ResourceManager.GetString("0x0015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Elemente und Daten werden gezählt ähnelt.
        /// </summary>
        internal static string _0x0016 {
            get {
                return ResourceManager.GetString("0x0016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zählen von Elementen und Daten abgeschlossen ähnelt.
        /// </summary>
        internal static string _0x0017 {
            get {
                return ResourceManager.GetString("0x0017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kopieren von Daten wird gestartet ähnelt.
        /// </summary>
        internal static string _0x0018 {
            get {
                return ResourceManager.GetString("0x0018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Elemente und Daten werden kopiert ähnelt.
        /// </summary>
        internal static string _0x0019 {
            get {
                return ResourceManager.GetString("0x0019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kopieren von Elemente und Daten abgeschlossen ähnelt.
        /// </summary>
        internal static string _0x001A {
            get {
                return ResourceManager.GetString("0x001A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vorgang abgebrochen ähnelt.
        /// </summary>
        internal static string _0x001B {
            get {
                return ResourceManager.GetString("0x001B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das eingegebene Datumsformat ist nicht gültig ähnelt.
        /// </summary>
        internal static string _0x001C {
            get {
                return ResourceManager.GetString("0x001C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Zielordner konnte nicht angelegt werden ähnelt.
        /// </summary>
        internal static string _0x001D {
            get {
                return ResourceManager.GetString("0x001D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler beim Anlegen des Zielordners ähnelt.
        /// </summary>
        internal static string _0x001E {
            get {
                return ResourceManager.GetString("0x001E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Projekt Öffnen fehlgeschlagen ähnelt.
        /// </summary>
        internal static string _0x001Fc {
            get {
                return ResourceManager.GetString("0x001Fc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler beim Lesen der Projektdatei.
        ///
        ///{0} ähnelt.
        /// </summary>
        internal static string _0x001Fm {
            get {
                return ResourceManager.GetString("0x001Fm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler beim Löschen von alten Dateien und Ordnern. ähnelt.
        /// </summary>
        internal static string _0x0020 {
            get {
                return ResourceManager.GetString("0x0020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Löschen von alten Dateien und Ordnern gestartet ähnelt.
        /// </summary>
        internal static string _0x0021 {
            get {
                return ResourceManager.GetString("0x0021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alten Dateien und Ordnern werden gelöscht ähnelt.
        /// </summary>
        internal static string _0x0022 {
            get {
                return ResourceManager.GetString("0x0022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Löschen von alten Dateien und Ordnern abgeschlossen ähnelt.
        /// </summary>
        internal static string _0x0023 {
            get {
                return ResourceManager.GetString("0x0023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alte Dateien und Ordner löschen? ähnelt.
        /// </summary>
        internal static string _0x0024c {
            get {
                return ResourceManager.GetString("0x0024c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sie haben die Option &quot;Alte Dateien und Ordner löschen&quot; gewählt.
        ///
        ///Alle Dateien und Ordner die in der Sicherungskopie, jedoch nicht in den Quellen vorhanden sind, werden unwiederruflich gelöscht. Sie werden nicht in die Papierkorb verschoben. Es erfolgt keine weitere Abfrage.
        ///
        ///Sind Sie sicher das Sie diesen Vorgang durchführen möchten? ähnelt.
        /// </summary>
        internal static string _0x0024m {
            get {
                return ResourceManager.GetString("0x0024m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler beim Schreiben in die Protokolldatei! ähnelt.
        /// </summary>
        internal static string _0x0025c {
            get {
                return ResourceManager.GetString("0x0025c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Beim Schreiben in die Protokolldatei &quot;{0}&quot; ist ein Fehler aufgetreten.
        ///
        ///{1}
        ///
        ///Sollen weitere Meldungen dieser Art unterdrückt werden? ähnelt.
        /// </summary>
        internal static string _0x0025m {
            get {
                return ResourceManager.GetString("0x0025m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auf Aktualisierung prüfen. ähnelt.
        /// </summary>
        internal static string _0x0026c {
            get {
                return ResourceManager.GetString("0x0026c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ihre Progammversion ist aktuell. ähnelt.
        /// </summary>
        internal static string _0x0026m {
            get {
                return ResourceManager.GetString("0x0026m", resourceCulture);
            }
        }
    }
}
