//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OLKI.Programme.QuBC.Project.LogFileWriter {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LogTemplates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LogTemplates() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OLKI.Programme.QuBC.src.Project.LogFileWriter.LogTemplates", typeof(LogTemplates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0}: Vorgang durch den Benutzer abgebrochen
        ///.. ähnelt.
        /// </summary>
        internal static string WriteCancel {
            get {
                return ResourceManager.GetString("WriteCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0}: Kopieren von Ordnern und Dateien abgeschlossen
        ///    Ordner:  {1:n0}
        ///    Dateien: {2:n0}
        ///    Bytes:   {3:n0}
        ///.. ähnelt.
        /// </summary>
        internal static string WriteCopyFinish {
            get {
                return ResourceManager.GetString("WriteCopyFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0}: Kopieren von Ordnern und Dateien gestartet
        ///.. ähnelt.
        /// </summary>
        internal static string WriteCopyStart {
            get {
                return ResourceManager.GetString("WriteCopyStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0}: Ermittle Anzahl von Dateien, Ordnern und Bytes zum Kopieren abgeschlossen
        ///    Ordner:  {1:n0}
        ///    Dateien: {2:n0}
        ///    Bytes:   {3:n0}
        ///.. ähnelt.
        /// </summary>
        internal static string WriteCountFinish {
            get {
                return ResourceManager.GetString("WriteCountFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0}: Ermittle Anzahl von Dateien, Ordnern und Bytes zum Kopieren gestartet
        ///.. ähnelt.
        /// </summary>
        internal static string WriteCountStart {
            get {
                return ResourceManager.GetString("WriteCountStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0}: Löschen von alten Ordnern und Dateien aus der Sicherung abgeschlossen
        ///.. ähnelt.
        /// </summary>
        internal static string WriteDeleteFinish {
            get {
                return ResourceManager.GetString("WriteDeleteFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0}: Löschen von alten Ordnern und Dateien aus der Sicherung gestartet
        ///.. ähnelt.
        /// </summary>
        internal static string WriteDeleteSart {
            get {
                return ResourceManager.GetString("WriteDeleteSart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0}: Ein Fehler ist aufgetreten
        ///    Quelle: {1}
        ///    Ziel:   {2}
        ///    Fehler: {3}
        ///.. ähnelt.
        /// </summary>
        internal static string WriteException {
            get {
                return ResourceManager.GetString("WriteException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0}: Vorgang erfolgreich abgeschlossen
        ///.. ähnelt.
        /// </summary>
        internal static string WriteFoot {
            get {
                return ResourceManager.GetString("WriteFoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Protokolldatei zur Datensicherung und Datenwiederherstellung
        ///------------------------------------------------------------
        ///
        ///Vorgang:
        ///[{0}] Datensicherung
        ///[{1}] Datenwiederherstellung
        ///
        ///Vorgang gestartet:
        ///    {2}
        ///
        ///Gewählte Optionen zur Datensicherung:
        ///    Ziel für Datensicherung: {3}
        ///    [{4}] Ordner für Laufwerk anlegen
        ///    Umgang mit vorhandenen Dateien: {5}
        ///    [{6}] Aufgabenumfang ermitteln
        ///    [{7}] Daten kopieren
        ///    [{8}] Alte Daten und Ordner im Sicherungsziel löschen
        ///
        ///Gewählte Option [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string WriteHead {
            get {
                return ResourceManager.GetString("WriteHead", resourceCulture);
            }
        }
    }
}
